# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from scalekit.v1.keys import keys_pb2 as scalekit_dot_v1_dot_keys_dot_keys__pb2


class KeyManagementServiceStub(object):
    """KeyManagementService provides operations for managing encryption keys
    including Data Encryption Keys (DEKs) and master key rotation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDEK = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/CreateDEK',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateDEKRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateDEKResponse.FromString,
                )
        self.RotateDEK = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/RotateDEK',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateDEKRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateDEKResponse.FromString,
                )
        self.ListDEKs = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/ListDEKs',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.ListDEKsRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.ListDEKsResponse.FromString,
                )
        self.DeleteDEK = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/DeleteDEK',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.DeleteDEKRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RotateMasterKey = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/RotateMasterKey',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateMasterKeyRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateMasterKeyResponse.FromString,
                )
        self.CreateMasterKey = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/CreateMasterKey',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateMasterKeyRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateMasterKeyResponse.FromString,
                )
        self.SetActiveDEK = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/SetActiveDEK',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveDEKRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveDEKResponse.FromString,
                )
        self.SetActiveMasterKey = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/SetActiveMasterKey',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveMasterKeyRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveMasterKeyResponse.FromString,
                )
        self.DestroyDEK = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/DestroyDEK',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.DestroyDEKRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DestroyMasterKey = channel.unary_unary(
                '/scalekit.v1.keys.KeyManagementService/DestroyMasterKey',
                request_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.DestroyMasterKeyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class KeyManagementServiceServicer(object):
    """KeyManagementService provides operations for managing encryption keys
    including Data Encryption Keys (DEKs) and master key rotation.
    """

    def CreateDEK(self, request, context):
        """CreateDEK creates a new Data Encryption Key (DEK) for an environment.
        If a DEK already exists, this will create a new version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateDEK(self, request, context):
        """RotateDEK creates a new DEK version for an environment.
        Re-encrypts existing data (oidc_client_secrets, connection client_secrets) and deprecates old DEK versions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDEKs(self, request, context):
        """ListDEKs lists DEKs for an environment with pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDEK(self, request, context):
        """DeleteDEK deprecates or permanently deletes a DEK version.
        Deprecated DEKs can still be used for decryption but not for encryption.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateMasterKey(self, request, context):
        """RotateMasterKey rotates the master key and rewraps all DEKs.
        This operation is idempotent and supports zero-downtime rotation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMasterKey(self, request, context):
        """CreateMasterKey creates a new master key version (in a non-active state).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActiveDEK(self, request, context):
        """SetActiveDEK sets a specific DEK version as active for an environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActiveMasterKey(self, request, context):
        """SetActiveMasterKey sets a specific master key version as active.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyDEK(self, request, context):
        """DestroyDEK permanently deletes a DEK version.
        WARNING: This operation is irreversible and will make data encrypted with this DEK unrecoverable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyMasterKey(self, request, context):
        """DestroyMasterKey permanently deletes a master key version.
        WARNING: This operation is irreversible and will make DEKs wrapped with this master key unrecoverable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDEK': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDEK,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateDEKRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateDEKResponse.SerializeToString,
            ),
            'RotateDEK': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateDEK,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateDEKRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateDEKResponse.SerializeToString,
            ),
            'ListDEKs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDEKs,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.ListDEKsRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.ListDEKsResponse.SerializeToString,
            ),
            'DeleteDEK': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDEK,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.DeleteDEKRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RotateMasterKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateMasterKey,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateMasterKeyRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateMasterKeyResponse.SerializeToString,
            ),
            'CreateMasterKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMasterKey,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateMasterKeyRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateMasterKeyResponse.SerializeToString,
            ),
            'SetActiveDEK': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActiveDEK,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveDEKRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveDEKResponse.SerializeToString,
            ),
            'SetActiveMasterKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActiveMasterKey,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveMasterKeyRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveMasterKeyResponse.SerializeToString,
            ),
            'DestroyDEK': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyDEK,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.DestroyDEKRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DestroyMasterKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyMasterKey,
                    request_deserializer=scalekit_dot_v1_dot_keys_dot_keys__pb2.DestroyMasterKeyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scalekit.v1.keys.KeyManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyManagementService(object):
    """KeyManagementService provides operations for managing encryption keys
    including Data Encryption Keys (DEKs) and master key rotation.
    """

    @staticmethod
    def CreateDEK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/CreateDEK',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateDEKRequest.SerializeToString,
            scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateDEKResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RotateDEK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/RotateDEK',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateDEKRequest.SerializeToString,
            scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateDEKResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDEKs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/ListDEKs',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.ListDEKsRequest.SerializeToString,
            scalekit_dot_v1_dot_keys_dot_keys__pb2.ListDEKsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDEK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/DeleteDEK',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.DeleteDEKRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RotateMasterKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/RotateMasterKey',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateMasterKeyRequest.SerializeToString,
            scalekit_dot_v1_dot_keys_dot_keys__pb2.RotateMasterKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMasterKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/CreateMasterKey',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateMasterKeyRequest.SerializeToString,
            scalekit_dot_v1_dot_keys_dot_keys__pb2.CreateMasterKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetActiveDEK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/SetActiveDEK',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveDEKRequest.SerializeToString,
            scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveDEKResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetActiveMasterKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/SetActiveMasterKey',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveMasterKeyRequest.SerializeToString,
            scalekit_dot_v1_dot_keys_dot_keys__pb2.SetActiveMasterKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyDEK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/DestroyDEK',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.DestroyDEKRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyMasterKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.keys.KeyManagementService/DestroyMasterKey',
            scalekit_dot_v1_dot_keys_dot_keys__pb2.DestroyMasterKeyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
