# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scalekit.v1.mcp import mcp_pb2 as scalekit_dot_v1_dot_mcp_dot_mcp__pb2


class McpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMcp = channel.unary_unary(
                '/scalekit.v1.mcp.McpService/CreateMcp',
                request_serializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.CreateMcpRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.CreateMcpResponse.FromString,
                )
        self.GetMcp = channel.unary_unary(
                '/scalekit.v1.mcp.McpService/GetMcp',
                request_serializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.GetMcpRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.GetMcpResponse.FromString,
                )
        self.ListMcp = channel.unary_unary(
                '/scalekit.v1.mcp.McpService/ListMcp',
                request_serializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.ListMcpRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.ListMcpResponse.FromString,
                )
        self.DeleteMcp = channel.unary_unary(
                '/scalekit.v1.mcp.McpService/DeleteMcp',
                request_serializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.DeleteMcpRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.DeleteMcpResponse.FromString,
                )


class McpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMcp,
                    request_deserializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.CreateMcpRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.CreateMcpResponse.SerializeToString,
            ),
            'GetMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMcp,
                    request_deserializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.GetMcpRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.GetMcpResponse.SerializeToString,
            ),
            'ListMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMcp,
                    request_deserializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.ListMcpRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.ListMcpResponse.SerializeToString,
            ),
            'DeleteMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMcp,
                    request_deserializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.DeleteMcpRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_mcp_dot_mcp__pb2.DeleteMcpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scalekit.v1.mcp.McpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class McpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.mcp.McpService/CreateMcp',
            scalekit_dot_v1_dot_mcp_dot_mcp__pb2.CreateMcpRequest.SerializeToString,
            scalekit_dot_v1_dot_mcp_dot_mcp__pb2.CreateMcpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.mcp.McpService/GetMcp',
            scalekit_dot_v1_dot_mcp_dot_mcp__pb2.GetMcpRequest.SerializeToString,
            scalekit_dot_v1_dot_mcp_dot_mcp__pb2.GetMcpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.mcp.McpService/ListMcp',
            scalekit_dot_v1_dot_mcp_dot_mcp__pb2.ListMcpRequest.SerializeToString,
            scalekit_dot_v1_dot_mcp_dot_mcp__pb2.ListMcpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.mcp.McpService/DeleteMcp',
            scalekit_dot_v1_dot_mcp_dot_mcp__pb2.DeleteMcpRequest.SerializeToString,
            scalekit_dot_v1_dot_mcp_dot_mcp__pb2.DeleteMcpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
