# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scalekit.v1.auditlogs import auditlogs_pb2 as scalekit_dot_v1_dot_auditlogs_dot_auditlogs__pb2


class AuditLogsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAuthRequests = channel.unary_unary(
                '/scalekit.v1.auditlogs.AuditLogsService/ListAuthRequests',
                request_serializer=scalekit_dot_v1_dot_auditlogs_dot_auditlogs__pb2.ListAuthLogRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_auditlogs_dot_auditlogs__pb2.ListAuthLogResponse.FromString,
                )


class AuditLogsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAuthRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditLogsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAuthRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuthRequests,
                    request_deserializer=scalekit_dot_v1_dot_auditlogs_dot_auditlogs__pb2.ListAuthLogRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_auditlogs_dot_auditlogs__pb2.ListAuthLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scalekit.v1.auditlogs.AuditLogsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuditLogsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAuthRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.auditlogs.AuditLogsService/ListAuthRequests',
            scalekit_dot_v1_dot_auditlogs_dot_auditlogs__pb2.ListAuthLogRequest.SerializeToString,
            scalekit_dot_v1_dot_auditlogs_dot_auditlogs__pb2.ListAuthLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
