# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scalekit.v1.workspaces import workspaces_pb2 as scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2


class WorkspaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWorkspace = channel.unary_unary(
                '/scalekit.v1.workspaces.WorkspaceService/CreateWorkspace',
                request_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.CreateWorkspaceResponse.FromString,
                )
        self.GetWorkspace = channel.unary_unary(
                '/scalekit.v1.workspaces.WorkspaceService/GetWorkspace',
                request_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceResponse.FromString,
                )
        self.GetCurrentWorkspace = channel.unary_unary(
                '/scalekit.v1.workspaces.WorkspaceService/GetCurrentWorkspace',
                request_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetCurrentWorkspaceRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceResponse.FromString,
                )
        self.UpdateWorkspace = channel.unary_unary(
                '/scalekit.v1.workspaces.WorkspaceService/UpdateWorkspace',
                request_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceResponse.FromString,
                )
        self.UpdateCurrentWorkspace = channel.unary_unary(
                '/scalekit.v1.workspaces.WorkspaceService/UpdateCurrentWorkspace',
                request_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateCurrentWorkspaceRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceResponse.FromString,
                )


class WorkspaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCurrentWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkspaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkspace,
                    request_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.CreateWorkspaceResponse.SerializeToString,
            ),
            'GetWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspace,
                    request_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceResponse.SerializeToString,
            ),
            'GetCurrentWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentWorkspace,
                    request_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetCurrentWorkspaceRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceResponse.SerializeToString,
            ),
            'UpdateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkspace,
                    request_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceResponse.SerializeToString,
            ),
            'UpdateCurrentWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCurrentWorkspace,
                    request_deserializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateCurrentWorkspaceRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scalekit.v1.workspaces.WorkspaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkspaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.workspaces.WorkspaceService/CreateWorkspace',
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.CreateWorkspaceRequest.SerializeToString,
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.CreateWorkspaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.workspaces.WorkspaceService/GetWorkspace',
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceRequest.SerializeToString,
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCurrentWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.workspaces.WorkspaceService/GetCurrentWorkspace',
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetCurrentWorkspaceRequest.SerializeToString,
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.GetWorkspaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.workspaces.WorkspaceService/UpdateWorkspace',
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceRequest.SerializeToString,
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCurrentWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.workspaces.WorkspaceService/UpdateCurrentWorkspace',
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateCurrentWorkspaceRequest.SerializeToString,
            scalekit_dot_v1_dot_workspaces_dot_workspaces__pb2.UpdateWorkspaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
