# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from scalekit.v1.secrets import secrets_pb2 as scalekit_dot_v1_dot_secrets_dot_secrets__pb2


class SecretServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSecret = channel.unary_unary(
                '/scalekit.v1.secrets.SecretService/CreateSecret',
                request_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.CreateSecretRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.CreateSecretResponse.FromString,
                )
        self.RotateSecret = channel.unary_unary(
                '/scalekit.v1.secrets.SecretService/RotateSecret',
                request_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.RotateSecretRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.RotateSecretResponse.FromString,
                )
        self.GetSecret = channel.unary_unary(
                '/scalekit.v1.secrets.SecretService/GetSecret',
                request_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.GetSecretRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.GetSecretResponse.FromString,
                )
        self.ListSecrets = channel.unary_unary(
                '/scalekit.v1.secrets.SecretService/ListSecrets',
                request_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.ListSecretsRequest.SerializeToString,
                response_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.ListSecretsResponse.FromString,
                )
        self.DeleteSecret = channel.unary_unary(
                '/scalekit.v1.secrets.SecretService/DeleteSecret',
                request_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.DeleteSecretRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SecretServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSecret,
                    request_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.CreateSecretRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.CreateSecretResponse.SerializeToString,
            ),
            'RotateSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateSecret,
                    request_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.RotateSecretRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.RotateSecretResponse.SerializeToString,
            ),
            'GetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecret,
                    request_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.GetSecretRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.GetSecretResponse.SerializeToString,
            ),
            'ListSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecrets,
                    request_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.ListSecretsRequest.FromString,
                    response_serializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.ListSecretsResponse.SerializeToString,
            ),
            'DeleteSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecret,
                    request_deserializer=scalekit_dot_v1_dot_secrets_dot_secrets__pb2.DeleteSecretRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scalekit.v1.secrets.SecretService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecretService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.secrets.SecretService/CreateSecret',
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.CreateSecretRequest.SerializeToString,
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.CreateSecretResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RotateSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.secrets.SecretService/RotateSecret',
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.RotateSecretRequest.SerializeToString,
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.RotateSecretResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.secrets.SecretService/GetSecret',
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.GetSecretRequest.SerializeToString,
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.GetSecretResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.secrets.SecretService/ListSecrets',
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.ListSecretsRequest.SerializeToString,
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.ListSecretsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scalekit.v1.secrets.SecretService/DeleteSecret',
            scalekit_dot_v1_dot_secrets_dot_secrets__pb2.DeleteSecretRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
